# Vagrantfile for setup a yaacc development box
# -*- mode: ruby -*-
# vi: set ft=ruby :
def motdTemplate
        motdTemplate =                 "__/\\\\\\________/\\\\\\_____/\\\\\\\\\\\\\\\\\\________/\\\\\\\\\\\\\\\\\\___________/\\\\\\\\\\\\\\\\\\________/\\\\\\\\\\\\\\\\\\_        \n"
    motdTemplate =  motdTemplate + " _\\///\\\\\\____/\\\\\\/____/\\\\\\\\\\\\\\\\\\\\\\\\\\____/\\\\\\\\\\\\\\\\\\\\\\\\\\______/\\\\\\////////______/\\\\\\////////__       \n"
    motdTemplate =  motdTemplate + "  ___\\///\\\\\\/\\\\\\/_____/\\\\\\/////////\\\\\\__/\\\\\\/////////\\\\\\___/\\\\\\/_____________/\\\\\\/___________      \n"
    motdTemplate =  motdTemplate + "   _____\\///\\\\\\/______\\/\\\\\\_______\\/\\\\\\_\\/\\\\\\_______\\/\\\\\\__/\\\\\\______________/\\\\\\_____________     \n"
    motdTemplate =  motdTemplate + "    _______\\/\\\\\\_______\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_\\/\\\\\\_____________\\/\\\\\\_____________    \n"
    motdTemplate =  motdTemplate + "     _______\\/\\\\\\_______\\/\\\\\\/////////\\\\\\_\\/\\\\\\/////////\\\\\\_\\//\\\\\\____________\\//\\\\\\____________   \n"
    motdTemplate =  motdTemplate + "      _______\\/\\\\\\_______\\/\\\\\\_______\\/\\\\\\_\\/\\\\\\_______\\/\\\\\\__\\///\\\\\\___________\\///\\\\\\__________  \n"
    motdTemplate =  motdTemplate + "       _______\\/\\\\\\_______\\/\\\\\\_______\\/\\\\\\_\\/\\\\\\_______\\/\\\\\\____\\////\\\\\\\\\\\\\\\\\\____\\////\\\\\\\\\\\\\\\\\\_ \n"
    motdTemplate =  motdTemplate + "        _______\\///________\\///________\\///__\\///________\\///________\\/////////________\\/////////__\n"
    motdTemplate =  motdTemplate + "\n"
    motdTemplate =  motdTemplate + "\n"
    motdTemplate =  motdTemplate + "Welcome to YAACC - vagrant development box\n"

  return motdTemplate
end 

def configTemplate
	configTemplate=		      "######################################################\n"        
        configTemplate=configTemplate+"##  Yaacc - Vagrant - Configurationfile             ##\n"
        configTemplate=configTemplate+"##                                                  ##\n"       
        configTemplate=configTemplate+"######################################################\n"
        configTemplate=configTemplate+"######################################################\n"
        configTemplate=configTemplate+"##             Developer setup                      ##\n"
        configTemplate=configTemplate+"######################################################\n"
        configTemplate=configTemplate+"developerName=\""+$YOURNAME+"\"\n"
        configTemplate=configTemplate+"developerEmail=\"<enter your email here>\"\n"        
        configTemplate=configTemplate+"developerPrivateRSAKeyName=\"id_rsa\"\n"
        configTemplate=configTemplate+"developerPublicRSAKeyName=\"id_rsa.pub\"\n"
        configTemplate=configTemplate+"######################################################\n"
        configTemplate=configTemplate+"##            Yaacc - Keystore secrets              ##\n"
        configTemplate=configTemplate+"######################################################\n"
        configTemplate=configTemplate+"keypass=\"mySuperSecretPassword\"\n"
        configTemplate=configTemplate+"keystorepass=\"mySuperSecretPassword\"\n"
        configTemplate=configTemplate+"repokeyalias=\"yaacc\"\n"
        configTemplate=configTemplate+"keystoreName=\"yaacc.de-release-key.keystore\"\n"
        configTemplate=configTemplate+"###################################################\n"
        configTemplate=configTemplate+"##            Yaacc - GitRepo                    ##\n"
        configTemplate=configTemplate+"###################################################\n"
        configTemplate=configTemplate+"yaaccRepo=\"ssh://"+$YOURNAME+"@git.code.sf.net/p/yaacc/code\"\n"
        configTemplate=configTemplate+"###################################################\n"
        configTemplate=configTemplate+"##            Froid                              ##\n"
        configTemplate=configTemplate+"###################################################\n"
        configTemplate=configTemplate+"fdroidServerRepo=\"git://gitorious.org/f-droid/fdroidserver.git\"\n"
        configTemplate=configTemplate+"fdroidDataRepo=\"git://gitorious.org/f-droid/"+$YOURNAME+"s-fdroiddata.git\"\n"
	return configTemplate
end


def instructions
	instructions=		  "Before restart vagrant setup your secrets:\n"       
        instructions=instructions+"1) copy the yaacc debug keystore file into the secret folder\n"
        instructions=instructions+"2) copy the yaacc release keystore file into the secret folder.\n"       
        instructions=instructions+"3) copy your private and public rsa key used for the authentication at fdroid repo  and yaacc repo into the secret folder\n"
        instructions=instructions+"4) modifiy the config file '" + $yaaccSecretPath + "/config'\n"
        instructions=instructions+"5) Restart vagrant..."
	return instructions
end


$yaaccSecretPath = "/home/" +ENV['USER']+ "/yaacc-secret"
$userSshPath = "/home/" +ENV['USER']+ "/.ssh"


if ARGV[0] == "up"
	if ! File.exist?("bootstrap.sh") || ! File.exist?($yaaccSecretPath) 
	  puts "################################################################\n"
	  puts "##  Y A A C C - D E V E L O P M E N T - B O X    S E T U P    ##\n"
	  puts "################################################################\n"
	end 

	# TODO: Set username on demand - problem with the given vagrant command
	#
	#puts "Please enter your desired username"
	#$YOURNAME = gets
	#puts "Username set to" + $YOURNAME 
	$YOURNAME = "YOUR_USER_NAME"

	if ! File.exist?("bootstrap.sh")
	  puts "Download box configuration file bootstrap.sh "
	  system("wget https://sourceforge.net/p/yaacc/code/ci/release-1.1.4/tree/vagrant/bootstrap.sh?format=raw -O bootstrap.sh")
	end

	if ! File.exist?($yaaccSecretPath)  
	  puts "Yaacc secret folder not found seems to be the first start...\n"
	  puts "Creating secret path at '" + $yaaccSecretPath + "'\n"
	  Dir::mkdir($yaaccSecretPath)
	  puts "Creating sample config file in secret folder: '" + $yaaccSecretPath + "/config'\n"
	  f = File.new($yaaccSecretPath + "/config", "w")
	  configTemplate.each_line{
	    |line|
	    f.write line
	  }
	  puts "Copying private key to secret folder\n"
	  system("cp "+$userSshPath+"/id_rsa "+$yaaccSecretPath)
	  puts "Copying public key to secret folder\n\n"
	  system("cp "+$userSshPath+"/id_rsa.pub "+$yaaccSecretPath)
	  
	  
	  puts instructions
	  exit
	else
	  puts "Found yaacc secret folder '" + $yaaccSecretPath + "'."   
	end

	if ! File.exist?($yaaccSecretPath+"/id_rsa")  

	  puts "Your id_rsa is missing !!!\n\n"

	  if File.exist?($userSshPath+"id_rsa")

	  	puts "Trying to copy your private key to secret folder\n"
	 	exec("cp "+$userSshPath+"/id_rsa "+$yaaccSecretPath)
	
		if File.exist?($yaaccSecretPath+"/id_rsa")
			puts "Private key successfully copied !\n\n"
		else
			puts "Unable to copy found key, please check executing rights !\n\n"
		end
	  
	  else
	
		puts "No private key found at all, did you create it ?\n\n"
	  	puts instructions
	  	exit
	  
	  end

	elsif ! File.exist?($yaaccSecretPath+"/id_rsa.pub")

	  puts "Your id_rsa.pub is missing !!!"

	  if File.exist?($userSshPath+"id_rsa.pub")

	  	puts "Trying to copy your public key to secret folder\n"
	 	exec("cp "+$userSshPath+"/id_rsa.pub "+$yaaccSecretPath)
	
		if File.exist?($yaaccSecretPath+"/id_rsa.pub")
			puts "Public key successfully copied !\n\n"
		else
			puts "Unable to copy found key, please check executing rights !\n\n"
		end
	  
	  else
	
		puts "No public key found at all, did you create it ?\n\n"
	  	puts instructions
	  	exit

	  end

	elsif ! File.exist?($yaaccSecretPath+"/debug.keystore")

	  puts "Your debug keystore is missing !!!"

	  if File.exist?($userSshPath+"/.android/debug.keystore")

	  	puts "Trying to copy your debug keystore to secret folder\n"
	 	exec("cp "+$userSshPath+"/.android/debug.keystore "+$yaaccSecretPath)
	
		if File.exist?($yaaccSecretPath+"/debug.keystore")
			puts "Debug keystore successfully copied !\n\n"
		else
			puts "Unable to copy found keystore, please check executing rights !\n\n"
		end
	  
	  else
	
		puts "No debug keystore found at all, did you create it ?\n\n"
	  	puts instructions
	  	exit

	  end

	elsif ! File.exist?($yaaccSecretPath+"/yaacc.de-release-key.keystore")

	  puts "Your release key is missing !!!\n\n"

	  puts instructions
	  exit

	# TODO: Checking the keystore is still needed
	#
	#elseif ! File.exist?($yaaccSecretPath+"/id_rsa.pub")
	#
	#  puts "Your id_rsa.pub is missing !!!"
	#  puts instructions
	#  exit

	else

	puts "Now starting vagrant box..."

	Vagrant::Config.run do |config|
	 config.vm.box = "yaacc-dev" 
	 config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	 config.vm.share_folder "yaacc-secret", "/mnt/yaacc-secret/" , $yaaccSecretPath , :create => false
	 config.vm.network :bridged, guest: 5555, host: 5555
	 config.vm.provision :shell, :inline => "echo '" + motdTemplate + "' > /etc/motd.tail"
	 config.vm.provision :shell, :path => "bootstrap.sh"
         config.vm.forward_port 49153, 49153
         config.vm.forward_port 43411, 43411
         config.vm.forward_port 4711, 4711
         config.vm.forward_port 5555, 5555
         config.vm.forward_port 80, 80
	 #config.vm.network :bridged, :bridge => 'eth0'

	end

	end

else 

Vagrant::Config.run do |config|
 config.vm.box = "yaacc-dev" 
 config.vm.box_url = "http://files.vagrantup.com/precise64.box"
 config.vm.share_folder "yaacc-secret", "/mnt/yaacc-secret/" , $yaaccSecretPath , :create => false
 config.vm.network :bridged, guest: 5555, host: 5555
 config.vm.provision :shell, :inline => "echo '" + motdTemplate + "' > /etc/motd.tail"
 config.vm.provision :shell, :path => "bootstrap.sh"
 config.vm.forward_port 49153, 49153
 config.vm.forward_port 43411, 43411
 config.vm.forward_port 4711, 4711
 config.vm.forward_port 5555, 5555
 config.vm.forward_port 80, 80
 #config.vm.network :bridged, :bridge => 'eth0'

end

end
